# Generated by Django 5.1.2 on 2025-04-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapviewer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parcel',
        ),
    ]
